import type { AppProps } from "next/app";
import Head from "next/head";
import "tailwindcss/tailwind.css";
import Header from "../components/header";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>DOG PICTURES APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/dog.svg" />
      </Head>
      <Header></Header>
      <Component className="font-sans" {...pageProps} />
    </>
  );
}

export default MyApp;
