import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>DOG PICTURES APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/dog.svg" />
      </Head>
      <span className="text-center text-2xl">DOG PICTURES APP</span>
    </div>
  );
};

export default Home;
